"""
llm/ollama_client.py
────────────────────
Low-level client that talks directly to the local Ollama HTTP API.

Responsibilities
----------------
* POST a prompt to http://localhost:11434/api/generate
* Stream or collect the full response text
* Handle connection / timeout / HTTP errors gracefully
* Return raw text so callers can decide how to process it
"""

import json
import requests

# Import central config values (URL, model, timeout, generation options)
from config import (
    OLLAMA_GENERATE_ENDPOINT,
    OLLAMA_MODEL,
    REQUEST_TIMEOUT,
    GENERATION_OPTIONS,
)


def generate(prompt: str, model: str = OLLAMA_MODEL) -> str:
    """
    Send *prompt* to Ollama and return the model's raw text reply.

    Parameters
    ----------
    prompt : str
        The fully-formed prompt string to send.
    model : str
        Name of the Ollama model to use (defaults to config value).

    Returns
    -------
    str
        The raw text generated by the model.

    Raises
    ------
    ConnectionError
        When Ollama is not reachable.
    TimeoutError
        When the request exceeds REQUEST_TIMEOUT seconds.
    RuntimeError
        For any other unexpected HTTP / parsing error.
    """

    # ── Build the request payload ──────────────────────────────────────────────
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,          # receive one complete JSON object, not SSE chunks
        "options": GENERATION_OPTIONS,
    }

    # ── Send request ───────────────────────────────────────────────────────────
    try:
        response = requests.post(
            OLLAMA_GENERATE_ENDPOINT,
            json=payload,
            timeout=REQUEST_TIMEOUT,
        )
        response.raise_for_status()     # raises HTTPError for 4xx / 5xx

    except requests.exceptions.ConnectionError:
        raise ConnectionError(
            "❌ Cannot reach Ollama. Make sure it is running:\n"
            "   ollama serve\n"
            f"   Expected endpoint: {OLLAMA_GENERATE_ENDPOINT}"
        )

    except requests.exceptions.Timeout:
        raise TimeoutError(
            f"⏱  Ollama did not respond within {REQUEST_TIMEOUT} seconds. "
            "Try a smaller prompt or a faster model."
        )

    except requests.exceptions.HTTPError as exc:
        raise RuntimeError(
            f"🔴 Ollama returned HTTP {response.status_code}: {exc}"
        )

    # ── Parse the JSON response ────────────────────────────────────────────────
    try:
        data = response.json()
    except json.JSONDecodeError:
        raise RuntimeError(
            "🔴 Ollama returned a non-JSON body. "
            f"Raw response (first 500 chars): {response.text[:500]}"
        )

    # Ollama's /api/generate response has a top-level "response" key
    raw_text: str = data.get("response", "")

    if not raw_text:
        raise RuntimeError(
            "🔴 Ollama returned an empty 'response' field. "
            f"Full payload: {data}"
        )

    return raw_text
